<?php

// Random PHP Code Generated by LLaMA

function getRandomColor() {
    $colors = array("red", "blue", "green", "yellow");
    return $colors[array_rand($colors)];
}

$color = getRandomColor();
echo $color;
